from ciphernator import Ciphernator

code = "DUENS RBIIE NGNNG IITNO UYLOI LXSOT PHWEH NHIWC MAOST VHENW TOAPC LIEEY ILNDI GSFOH UYULP LNOIN TGRHL EEPSN HISFH IASSE EONPE OMNTE TAYHR EAEYD RVYER HBEGS NIRSO BHUTG TGHAE EDRAS SEDAA NSIAR OWUYA SRTES RVIYR FMMEA MNATU LNERD VEDOF IIRTU LFHUV EEAAN THNHD USEAR NYGIE SDHBS DULUI ETGTH MHSER PIIIT SFEHA BFSRT COAME LDLVM IOGNR GNEME DAANP YEONN DAUFI RATKM OEMDI IONON GTHEE THROW OSFES IINHX STTIH XGLHI OTVMH ETTIH REETR HIELF OLUFH RYTHO EUFRO BTUHR PAEPA AIRIR GLSHF TMIAR NMTEN KDIDM SIPTO UANYD OSRFT THHEE SRSEA AOWNA WENOY DSAEC ARDTS EDEFE EAAC"

main = Ciphernator(code)

main.solve_transposition_simple()
print("'" + main.get_output() + "'")
